
export const AGENCY_PRICE_INCREMENT_PARAMETER = 0.01;

export const BOT_INVESTMENT_PARAMETER = 1;
export const BOT_LOSS_AVERSION_PARAMETER = 0.1;
export const BOT_STOCK_CLEARANCE_PARAMETER = 0.5;

export const PORTFOLIO_MINIMUM_BALANCE = 10000;
export const PORTFOLIO_STARTING_BALANCE = 100000;
export const STOCK_DUMP_THRESHOLD = 10;

export const MARKET_BASE = 1000;
export const DATE_LIMIT = 20;
export const SLOT_DURATION = 1;

export const DIVIDEND_FACTOR = 5;

